### ISSUE TITLE
not getting history data off device

### ISSUE THREAD

**Issue by Commander1024** [chaim-zax/gq-gmc-control#5]
Ohai,

I bought myself a  GMC 320 Plus (GMC-320Re 4.53). Most of this tools function work on this device and give reasonable output like -i, -o, -O, -G, -T and --heartbeat etc.

But it seems like it cannot get the history:
> python2 ./gq-gmc-control.py -p /dev/ttyUSB0 -d
> device found: GMC-320Re 4.53
> storing data to '/tmp/tmpTFmCQ4.bin'
> address: 0x000000, size: 4096, total size: 1 bytes (0%)
> address: 0x001000, size: 4096, total size: 2 bytes (0%)
> address: 0x002000, size: 4096, total size: 3 bytes (0%)
> address: 0x003000, size: 4096, total size: 4 bytes (0%)

This run won't finish (within a reasonable time).

resulting .bin file looks pretty empty:

> hexdump gq-gmc-log.bin                        
> 0000000 0055 0000 ff00 ffff ffff ffff ffff ffff
> 0000010 ffff ffff ffff ffff ffff ffff ffff ffff
> *
> 0000080 ff55 ffff ffff ffff ffff ffff ffff ffff
> 0000090 ffff ffff ffff ffff ffff ffff ffff ffff
> *
> 00001f0 ffff ffff 00ff                         
> 00001f5

Is there any additional info I can provide for debugging?

**Comment by chaim-zax** [comment]
Unfortunately from revision GMC-500+Re 2.x on they changed to protocol, the library was designed using the Re 1.x firmware. See issue #3 for more info.

**Comment by takosalad** [comment]
I have the exact same problem as the OP. I also tried https://github.com/ThomasHabets/gq-gmc-control but it doesn't change anything.
GMC-300E.
Help please, I need to get the data off this device to the linux workstation ASAP!
What is the company doing?
